version: "3"
networks:
  test9:
    driver: bridge
    ipam:
      config:
        - subnet: 15.0.0.1/24
services:





  fastify:
    networks:
      test9:
          ipv4_address: 15.0.0.3     
    build: ../backend
 
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ../backend:/usr/src/app

  db:
    image: mysql:5.7
    restart: always
    networks:
      test9:
          ipv4_address: 15.0.0.4
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      DB_HOST: db
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

      # Password for root access
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  
# Names our volume
volumes:
  my-db:



