const ActionTypes={
    ASYNC_START:"ASYNC_START",
    ASYNC_END:"ASYNC_END",


    LOGIN_TYPE:{
        LOGIN:"LOGIN",
        LOGIN_SUCCESS: "LOGIN_SUCCESS",
        LOGIN_PENDING: "LOGIN_PENDING",
        UPDATE_PROFILE:"UPDATE_PROFILE",
        UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
        UPDATE_PROFILE_PENDING: "UPDATE_PROFILE_PENDING",
        LOGOUT:"LOGOUT",
        LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
        LOGOUT_PENDING: "LOGOUT_PENDING",


    },


    ADMIN_TYPE:{

        GET_ENTERPRISE:"GET_ENTERPRISE",
        GET_ENTERPRISE_SUCCESS:"GET_ENTERPRISE_SUCCESS",
        GET_ENTERPRISE_PENDING:"GET_ENTERPRISE_PENDING",
        DELETE_ENTERPRISE: "DELETE_ENTERPRISE",
        DELETE_ENTERPRISE_SUCCESS:"DELETE_ENTERPRISE_SUCCESS",
        DELETE_ENTERPRISE_PENDING:"DELETE_ENTERPRISE_PENDING",
        ADD_ENTERPRISE: "ADD_ENTERPRISE",
        ADD_ENTERPRISE_SUCCESS: "ADD_ENTERPRISE_SUCCESS",
        ADD_ENTERPRISE_PENDING: "ADD_ENTERPRISE_PENDING"
        
    }
}

export default ActionTypes