const ActionTypes={
    ASYNC_START:"ASYNC_START",
    ASYNC_END:"ASYNC_END",
    ANIMALS_TYPE:{
        INSERT_ANIMAL:  "INSERT_ANIMAL",
        UPDATE_ANIMAL: "UPDATE_ANIMAL",
        INSERT_ANIMAL_SUCCESS: "INSERT_ANIMAL_SUCCESS",
        UPDATE_ANIMAL_SUCCESS: "UPDATE_ANIMAL_SUCCESS",
        INSERT_ANIMAL_PENDING: "INSERT_ANIMAL_PENDING",
        UPDATE_ANIMAL_PENDING: "UPDATE_ANIMAL_PENDING",
        FETCH_ANIMALS: "FETCH_ANIMALS",
        FETCH_ANIMAL: "FETCH_ANIMAL",
        FETCH_ANIMALS_SUCCESS: "FETCH_ANIMALS_SUCCESS",
        FETCH_ANIMALS_PENDING: "FETCH_ANIMALS_PENDING",
        FETCH_CURRENT: "FETCH_CURRENT",
        FETCH_MUNICIPIS: "FETC_MUNICIPIS",
        FETCH_MUNICIPIS_SUCCESS: "FETCH_MUNICIPIS_SUCCESS",
        FETCH_MUNICIPIS_PENDING: "FETCH_MUNICIPIS_PENDING",
        FETCH_PROVINCIES: "FETC_PROVINCIES",
        FETCH_PROVINCIES_SUCCESS: "FETCH_PROVINCIES_SUCCESS",
        FETCH_PROVINCIES_PENDING: "FETCH_PROVINCIES_PENDING"

    },
    RIVIA_TYPE:{
        INSERT_RIVIA: "INSERT_RIVIA",
        FETCH_RIVIA: "FETCH_RIVIA",
        FETCH_RIVIA_SUCCESS: "FETCH_RIVIA_SUCCESS"
    },

    LOGIN_TYPE:{
        LOGIN:"LOGIN",
        LOGIN_SUCCESS: "LOGIN_SUCCESS",
        LOGIN_PENDING: "LOGIN_PENDING",
        UPDATE_PROFILE:"UPDATE_PROFILE",
        UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
        UPDATE_PROFILE_PENDING: "UPDATE_PROFILE_PENDING"


    },
    PROFILE_TYPE:{

    }
}

export default ActionTypes